#include<bits/stdc++.h>using namespace std;int fst(string& a){    int n=a[a.size()-1]-'0';    a.pop_back();    return n;}int snd(string& b){    int m=b[b.size()-1]-'0';    b.pop_back();    return m;}string sum(string& a, string& b){     string c;     int carry=0,x,t;    if(a.size()>b.size())    {        x=a.size()- b.size();        reverse(b.begin(), b.end());        for(int i=1; i<=x; i++)        {            b.push_back('0');        }        reverse(b.begin(), b.end());    }    else if(b.size()>a.size())        {            x=b.size()-a.size();            reverse(a.begin(), a.end());            for(int i=1; i<=x; i++)            {                a.push_back('0');            }            reverse(a.begin(), a.end());        }        x=a.size();    for(int i=1; i<=x; i++)    {        t=carry+fst(a)+snd(b);        if(t>9)carry=1;        else carry=0;        c.push_back(t%10+'0');    }    if(carry)c.push_back(carry+'0');    reverse(c.begin(), c.end());
    return c;}string mul(string a, string b){    string ex;     int x,cnt=0;    /*if(a.size()>b.size())    {        x=a.size()-b.size();        reverse(b.begin(), b.end());        for(int i=1; i<=x; i++)        {            b.push_back('0');        }        reverse(b.begin(), b.end());    }    else if(b.size()>a.size())        {            x=b.size()-a.size();            reverse(a.begin(), a.end());            for(int i=1; i<=x; i++)            {                a.push_back('0');            }            reverse(a.begin(), a.end());        }*/        //x=a.size();        for(int i=b.size()-1; i>=0; i--)        {            string ci="";            int carry=0,t=0;            for(int j=a.size()-1; j>=0; j--)            {                t=carry+ ( (b[ i ] -'0') *  (a[ j ]-'0') );                carry=t/10;                ci.push_back(t%10+'0');            }            reverse(ci.begin(), ci.end());            for(int k=1; k<=cnt; k++)            {                ci.push_back('0');            }
            for(int l=0; l<x; l++)            {                ex=sum(ex, ci);            }            cnt++;        }

    return ex;}int main(){    string a,b,d;    cin>>a>>b;
    int start_s=clock();    d=mul(a, b);    for(int j=0; j<d.size(); j++)    {
        cout<<d[j];    }    cout<<endl;
    int stop_s=clock();
    cout << "Time: " << (stop_s-start_s)/double(CLOCKS_PER_SEC)*1000<<" ms" << endl;    return 0;}
